### ISSUE TITLE
Depends on Clordane, which depends on nonexistent "receptacle"

### ISSUE THREAD

**Issue by akanouras** [robert-strandh/SICL#175]
Hello,

having cloned SICL, Cluster, Clordane (not mentioned in the README), Concrete-Syntax-Tree, Eclector, Trucler into ~/.roswell/local-projects/ , I'm getting this:

```
$ ros lisp=sbcl run -e '(asdf:load-system "sicl-boot")'

(...)

debugger invoked on a ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread
#<THREAD "main thread" RUNNING {10008B80D3}>:
  Component #:RECEPTACLE not found, required by #<SYSTEM "clordane">

```

**Comment by no-defun-allowed** [comment]
The system `receptacle` exists in https://github.com/lokedhs/containers which is not on Quicklisp. I had forked Clordane to use `safe-queue` which is on Quicklisp, but removed it after finding the receptacle repository; maybe I should reproduce those changes since finding receptacle is trickier than usual. Or just update the README if Clordane isn't mentioned in it either.

Also, I haven't used Roswell, but if it quits after loading the system, then there won't be much to see. `(sicl-boot:boot)` starts off bootstrapping and returns a boot environment.

**Comment by robert-strandh** [comment]
I removed the dependency on Clordane.  

Thanks for pointing this out.
