### ISSUE TITLE
:SICL-BOOT won't compile due to evaluation-environment-mixin not being defined

### ISSUE THREAD

**Issue by zardoz03** [robert-strandh/SICL#237]
If I were to clone SICL and Acclimation to ql:*quicklisp-home*/local-projects, and quickload closer-mop and documentation-utils, `(asdf:load-system :sicl-boot)` fails due to https://github.com/robert-strandh/SICL/blob/master/Code/Environment-Clostrum/environment.lisp#L45 not being defined within any part of the dependencies or SICL itself.

**Comment by robert-strandh** [comment]
The SICL bootstrapping procedure is currently broken, because of modifications to
Clostrum that I haven't had time to keep up with.  However, even when it is not
broken, there is not a lot you can do with it once the current bootstrapping procedure
finishes its execution.  SICL is still not complete.
