### ISSUE TITLE
Hacking Cleavir

### ISSUE THREAD

**Issue by larsbrinkhoff** [robert-strandh/SICL#30]
Hej!

I'm interested in using Cleavir to generate Emacs bytecodes.  Where do I start?

Thanks!

**Comment by larsbrinkhoff** [comment]
And quite possibly, rebase all of [emacs-cl](http://github.com/larsbrinkhoff/emacs-cl) on top of SICL.

**Comment by robert-strandh** [comment]
I am sorry I failed to respond to this issue.

I don't know Emacs bytecodes very well, so it is hard for me to give a
detailed response.  I am guessing they are not very low level, so it
would probably be best to generate code starting directly from HIR
which is what the second phase of the compiler generates.  The reason
I think that is that more transformations generate lower-level code,
exposing things like address calculations, and I am guessing Emacs
Lisp bytecodes are at a higher level than that.

In the first phase, it generates ASTs from source code.  For that to
work, you need an object that represents a global environment and you
need to have methods specialized to the class of this object so that
the AST generator can find things like macro expanders, type
definitions, values of constants, etc.

I am willing to help you out if you are still interested in such a
project.

**Comment by larsbrinkhoff** [comment]
Thanks!

I'm mostly interested in learning about the interfaces between the machine-independent parts of the compiler, and the back end.  Just some vague pointers into the source tree would be great.

I'm not suggesting you should have to learn anything about Emacs bytecodes; that would be my job.  But FYI, the bytecode engine works as a stack machine with opcodes generally operating on the one or two top stack items.  A function invocation creates a new stack frame with arguments, lexical variables, and temporary values.

I'm still interested, it's just on the back-burner now.
